# Generated by Django 6.0.2 on 2026-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography or description of the school'),
        ),
    ]
