# Generated by Django 6.0.2 on 2026-02-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_light', models.ImageField(blank=True, upload_to='branding/%Y/%m/')),
                ('logo_dark', models.ImageField(blank=True, upload_to='branding/%Y/%m/')),
                ('favicon', models.ImageField(blank=True, upload_to='branding/')),
                ('og_image', models.ImageField(blank=True, help_text='Default social sharing image', upload_to='branding/')),
                ('footer_logo', models.ImageField(blank=True, upload_to='branding/')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(default='#0A4D8C', max_length=7)),
                ('secondary', models.CharField(default='#E67E22', max_length=7)),
                ('accent', models.CharField(default='#2ECC71', max_length=7)),
                ('surface', models.CharField(default='#FFFFFF', max_length=7)),
                ('text', models.CharField(default='#1A1A1A', max_length=7)),
                ('text_muted', models.CharField(default='#6C757D', max_length=7)),
                ('success', models.CharField(default='#28A745', max_length=7)),
                ('warning', models.CharField(default='#FFC107', max_length=7)),
                ('error', models.CharField(default='#DC3545', max_length=7)),
                ('dark_primary', models.CharField(blank=True, max_length=7)),
                ('dark_surface', models.CharField(blank=True, max_length=7)),
                ('dark_text', models.CharField(blank=True, max_length=7)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='FontPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_font', models.CharField(default='Inter', max_length=100)),
                ('body_font', models.CharField(default='system-ui', max_length=100)),
                ('heading_weights', models.CharField(default='400,600,700', max_length=50)),
                ('body_weights', models.CharField(default='400,500', max_length=50)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='tenants.tenant')),
            ],
        ),
    ]
