# Generated by Django 6.0.2 on 2026-02-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpalette',
            name='border',
            field=models.CharField(default='#E5E7EB', max_length=7),
        ),
        migrations.AddField(
            model_name='colorpalette',
            name='footer_bg',
            field=models.CharField(default='#111827', max_length=7),
        ),
        migrations.AddField(
            model_name='colorpalette',
            name='footer_text',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='colorpalette',
            name='surface_alt',
            field=models.CharField(default='#F8F9FA', max_length=7),
        ),
    ]
