# Generated by Django 6.0.2 on 2026-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_colorpalette_border_colorpalette_footer_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpalette',
            name='primary_dark',
            field=models.CharField(default='#003ACC', max_length=7),
        ),
        migrations.AddField(
            model_name='colorpalette',
            name='primary_glow',
            field=models.CharField(default='rgba(0, 81, 255, 0.35)', max_length=50),
        ),
        migrations.AddField(
            model_name='colorpalette',
            name='primary_light',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='colorpalette',
            name='secondary_light',
            field=models.CharField(default='#1A2D5A', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='accent',
            field=models.CharField(default='#00D4FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='primary',
            field=models.CharField(default='#0051FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='secondary',
            field=models.CharField(default='#0F1D40', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='surface',
            field=models.CharField(default='#F8FAFD', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='surface_alt',
            field=models.CharField(default='#EFF4FB', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='text',
            field=models.CharField(default='#1A1A2E', max_length=7),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='text_muted',
            field=models.CharField(default='#64748B', max_length=7),
        ),
    ]
