# Generated by Django 6.0.2 on 2026-02-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('media_items', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CachedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(db_index=True, help_text='Original ID in SMS', max_length=50)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('featured_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('registration_link', models.URLField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'unique_together': {('tenant', 'sms_id')},
            },
        ),
        migrations.CreateModel(
            name='CachedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(db_index=True, help_text='Original ID in SMS', max_length=50)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('featured_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'unique_together': {('tenant', 'sms_id')},
            },
        ),
        migrations.CreateModel(
            name='CachedNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(db_index=True, help_text='Original ID in SMS', max_length=50)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('featured_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('attachment_url', models.URLField(blank=True, help_text='Link to PDF etc.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'unique_together': {('tenant', 'sms_id')},
            },
        ),
        migrations.CreateModel(
            name='CachedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('tenant', 'sms_id')},
            },
        ),
        migrations.CreateModel(
            name='CachedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('tenant', 'sms_id')},
            },
        ),
    ]
