# Generated by Django 6.0.2 on 2026-03-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedprogram',
            name='featured_image',
            field=models.URLField(blank=True, help_text='Featured/banner image URL for this program'),
        ),
    ]
