# Generated by Django 6.0.2 on 2026-03-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0002_add_featured_image_to_cachedprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedalbum',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='cachedevent',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
        migrations.AlterField(
            model_name='cachednews',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
        migrations.AlterField(
            model_name='cachednotice',
            name='attachment_url',
            field=models.FileField(blank=True, help_text='Upload PDF etc.', null=True, upload_to='notices/'),
        ),
        migrations.AlterField(
            model_name='cachednotice',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
        migrations.AlterField(
            model_name='cachedprogram',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured/banner image for this program', null=True, upload_to='programs/'),
        ),
        migrations.AlterField(
            model_name='cachedprogram',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='program_icons/'),
        ),
        migrations.AlterField(
            model_name='cachedstaff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
