# Generated by Django 6.0.2 on 2026-03-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0003_alter_cachedalbum_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedalbum',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='albums/covers/'),
        ),
        migrations.CreateModel(
            name='AlbumMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='albums/media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_media', to='cache.cachedalbum')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
