# Generated by Django 6.0.2 on 2026-03-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0004_alter_cachedalbum_cover_image_albummedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummedia',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_media', to='cache.cachedalbum'),
        ),
    ]
