# Generated by Django 6.0.2 on 2026-02-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero with CTA'), ('features', 'Features/Programs Grid'), ('stats', 'Statistics/Highlights'), ('news', 'Latest News'), ('events', 'Upcoming Events'), ('notices', 'Important Notices'), ('testimonials', 'Testimonials'), ('gallery', 'Gallery'), ('achievements', 'Achievements'), ('staff', 'Faculty & Staff'), ('cta', 'Call to Action')], max_length=30),
        ),
    ]
