# Generated by Django 6.0.2 on 2026-02-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Unique identifier for this menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, help_text='External or internal path', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('target_blank', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.menu')),
                ('page', models.ForeignKey(blank=True, help_text='Link to a local page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
